# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kensley Blaise  
email: k.blaise@uea.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to KB website!
twitter_username: KensleyBlaise
github_username: KensleyBlaise
minimal_mistakes_skin: air
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : 
  avatar : "/assets/images/kensley-github.jpg"
  bio    : "Economics Ph.D. student at the University of East Anglia (UEA. Chevening scholar."
  links:
    - label: "My email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:k.blaise@uea.ac.uk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/KensleyBlaise"
   # -  label: "GitHub"
     #  icon: "fab fa-fw fa-github"
     #  url: "https://github.com/KensleyBlaise"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kensley-blaise-b18628176/"
     #  - label: "Instagram"
    #    icon: "fab fa-fw fa-instagram"
      #  url: "https://instagram.com/"
  #footer:
   
   #  - label: "Twitter"
     #  icon: "fab fa-fw fa-twitter-square"
     #  url: "https://twitter.com/"
    # - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    #  - label: "Instagram"
    #    icon: "fab fa-fw fa-instagram"
      #  url: "https://instagram.com/"
 
#  defaults:
  # _posts
 #   - scope:
    #  path: ""
   #    type: posts
     # values:
    #  layout: single
     #  author_profile: true
      #  read_time: true
      # comments: true
     #  share: true
      #   related: true
 # _pages
 #  - scope:
   #  path: "_pages"
    #  type: pages
  #  values:
   #   layout: single
    # author_profile: true

  # category_archive:
  #    type: liquid
  #   path: /categories/
  # tag_archive:
  #   type: liquid
   #  path: /tags/

#command to remove the feed in the footer of the webpage
atom_feed:
  hide: true
.masthead {
-  position: relative;
+  position: fixed;
+  top: 0;
+  width: 100%;
+  height: $masthead-height;
+
   border-bottom: 1px solid $border-color;
   -webkit-animation: intro 0.3s both;
           animation: intro 0.3s both;
@@ -16,6 +20,7 @@
     @include clearfix;
     padding: 0.1em 0.1em 0.1em;
     font-family: $sans-serif-narrow;
+    background-color: #fff;

     @include breakpoint($x-large) {
       max-width: $x-large;
diff --git a/_sass/_page.scss b/_sass/_page.scss
index e95f07d..487c5c7 100644
--- a/_sass/_page.scss
+++ b/_sass/_page.scss
@@ -6,6 +6,7 @@
   @include container;
   @include clearfix;
   margin-top: 2em;
+  padding-top: $masthead-height;
   padding-left: 1em;
   padding-right: 1em;
   animation: intro 0.3s both;
diff --git a/_sass/_sidebar.scss b/_sass/_sidebar.scss
index 9df17ea..712498a 100644
--- a/_sass/_sidebar.scss
+++ b/_sass/_sidebar.scss
@@ -8,6 +8,7 @@

 .sidebar {
   @include clearfix();
+  padding-top: $masthead-height;
   margin-bottom: 1em;

   @include breakpoint($large) {
diff --git a/_sass/_variables.scss b/_sass/_variables.scss
index d14acf0..eec32ee 100644
--- a/_sass/_variables.scss
+++ b/_sass/_variables.scss
@@ -139,3 +139,5 @@ $box-shadow                 : 0 1px 1px rgba(0, 0, 0, 0.125);
 $navicon-width              : 28px;
 $navicon-height             : 4px;
 $global-transition          : all 0.2s ease-in-out;
+
+$masthead-height            : 50px;
